### ISSUE TITLE
Fix BMI update_frac method

### ISSUE THREAD

**Issue by mdpiper** [csdms-contrib/fastmech#11]
The BMI *update_frac* method updates the model state by a fraction of a time step. Here, it doesn't fail, but it only updates the model by a full time step, no matter what fraction is supplied. See, e.g., the output from running *irf_test*, lines 41-46.

**Comment by rmcd-mscb** [comment]
_update_frac_ works now latest _irf_test2_ line 64.  Thanks Mark
